labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "duplicate"
    color: "cfd3d7"
    description: "This issue or pull request already exists"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "invalid"
    color: "e4e669"
    description: "This doesn't seem right"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"
  - name: "frontend"
    color: "0366d6"
    description: "Frontend related changes"
  - name: "backend"
    color: "28a745"
    description: "Backend related changes"
  - name: "database"
    color: "ff6b6b"
    description: "Database related changes"
  - name: "api"
    color: "6f42c1"
    description: "API related changes"
  - name: "ui/ux"
    color: "fbca04"
    description: "User interface or experience changes"
  - name: "security"
    color: "d93f0b"
    description: "Security related changes"
  - name: "performance"
    color: "00d4aa"
    description: "Performance improvements"
  - name: "testing"
    color: "ffa500"
    description: "Testing related changes"
  - name: "dependencies"
    color: "0366d6"
    description: "Dependency updates"
  - name: "breaking-change"
    color: "d73a4a"
    description: "Breaking changes"
  - name: "feature"
    color: "a2eeef"
    description: "New features"
  - name: "fix"
    color: "28a745"
    description: "Bug fixes"
  - name: "chore"
    color: "fef2c0"
    description: "Maintenance tasks"
  - name: "refactor"
    color: "6f42c1"
    description: "Code refactoring"
  - name: "ci/cd"
    color: "0366d6"
    description: "CI/CD related changes"
  - name: "deployment"
    color: "00d4aa"
    description: "Deployment related changes"
