name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
template: |
  ## 🎉 Release v$RESOLVED_VERSION

  $CHANGES

  ## 📋 Resumo das Mudanças

  $CHANGES

  ## 🔧 Melhorias Técnicas

  $CHANGES

  ## 🐛 Correções

  $CHANGES

  ## 📚 Documentação

  $CHANGES

  ## 🚀 Como Atualizar

  1. Faça backup do seu banco de dados
  2. Atualize as dependências: `npm install`
  3. Execute as migrações: `npx prisma migrate deploy`
  4. Reinicie os serviços

  ## 📦 Downloads

  - [Source Code](https://github.com/seu-usuario/traffic-manager-hub/archive/v$RESOLVED_VERSION.zip)
  - [Release Notes](https://github.com/seu-usuario/traffic-manager-hub/releases/tag/v$RESOLVED_VERSION)

  ---

  **Obrigado a todos os contribuidores! 🙏**
